name: Seal Scuba
favicon: null
layout_spectrum: 0.5917295108083636
typography_spectrum: 0.6732713645324111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7098366615828127
  lightness: 0.7945182649418712
  saturation: 0.2770977590698749
  rhythmicContrast: 0.38387130317278206
purpose: []
